import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ChatStateProvider from "./commons/providers/chat-state/chat-state.provider";
import ModalProvider from "./commons/providers/modal/modal.provider";
import ReactQueryProvider from "./commons/providers/react-query/react-query.provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <ChatStateProvider>
            <ModalProvider>{children}</ModalProvider>
          </ChatStateProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
